# Generated by Django 2.2.4 on 2019-08-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='contact',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
