# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0002_auto_20180815_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='project.png', upload_to=''),
        ),
    ]
