# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0004_auto_20180817_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='imagephone',
            field=models.ImageField(default='d.png', upload_to='phoneprojects'),
            preserve_default=False,
        ),
    ]
