# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0006_project_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='LIVE',
            field=models.BooleanField(default=False),
        ),
    ]
