# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0007_project_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repolink',
            field=models.TextField(default='#'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
