# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0008_auto_20180819_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skill',
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='folio.Skill'),
        ),
    ]
