# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0010_auto_20180827_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField()),
                ('isp', models.TextField()),
                ('country', models.TextField()),
                ('device', models.TextField()),
                ('os', models.TextField()),
                ('browser', models.TextField()),
                ('city', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='projects', to='folio.Skill'),
        ),
    ]
