# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0012_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.TextField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('InfoSec', 'InfoSec')], default='Backend'),
            preserve_default=False,
        ),
    ]
