# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0013_skill_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='referer',
            field=models.TextField(default='Old'),
            preserve_default=False,
        ),
    ]
