# Generated by Django 2.1.9 on 2019-07-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0014_visit_referer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='imagephone',
            new_name='image_phone',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='repolink',
            new_name='repo_link',
        ),
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.TextField(),
        ),
    ]
