# Generated by Django 2.1.9 on 2019-07-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0015_auto_20190713_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='LIVE',
            new_name='live',
        ),
    ]
