# Generated by Django 2.1.9 on 2019-07-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0016_auto_20190713_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='children_type',
            field=models.TextField(default='skills'),
        ),
        migrations.AddField(
            model_name='skill',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='folio.Skill'),
        ),
    ]
