# Generated by Django 2.1.9 on 2019-07-13 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0017_auto_20190713_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('icon_type', models.TextField(choices=[('fab', 'Brand Icons'), ('fas', 'Solid Icons'), ('far', 'Regular Icons'), ('fal', 'Light Icons')])),
                ('icon', models.TextField()),
                ('text', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='folio.Skill'),
        ),
    ]
