# Generated by Django 2.2.3 on 2019-07-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0018_auto_20190713_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('title', models.TextField()),
                ('secondaryTitle', models.TextField()),
                ('backgroundImage', models.ImageField(upload_to='')),
                ('aboutMeHead', models.TextField()),
                ('aboutMeBody', models.TextField()),
                ('extraMd', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
